### ISSUE TITLE
fatal error: 'crack.h' file not found

### ISSUE THREAD

**Issue by onkelhoy** [danielsen/node-cracklib#6]
Clean project, 
npm install cracklib

my index file:
```
const cracklib = require("cracklib");
console.log(cracklib.fascistCheck("pA5sword"));
```
Node version `12.18.4`
NPM version `6.14.6`
environment: `macOS Big Sur v11.1`

Error stack
```
  CXX(target) Release/obj.target/cracklib/src/cracklib.o
../src/cracklib.cpp:21:10: fatal error: 'crack.h'
      file not found
#include <crack.h>
         ^~~~~~~~~
1 error generated.
make: *** [Release/obj.target/cracklib/src/cracklib.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/henry.pap/Documents/PPMS/package_testing/node_modules/cracklib
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN package_testing@1.0.0 No description
npm WARN package_testing@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cracklib@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cracklib@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/henry.pap/.npm/_logs/2021-01-28T09_36_09_700Z-debug.log
```

**Comment by danielsen** [comment]
The `cracklib` development headers are missing on your system. I'm not a Mac user myself but I if your using `brew` or some similar package manger check to see if you can install `cracklib-devel` (or whatever the development package name is called). If your package manager doesn't have a development package, you can try installing from source as described here: https://github.com/cracklib/cracklib/tree/master/src

**Comment by onkelhoy** [comment]
Yes I saw that later, my bad!
